// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolvoExam.Data;

namespace VolvoExam.Data.Migrations
{
    [DbContext(typeof(VolvoExamDbContext))]
    partial class VolvoExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseSerialColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VolvoExam.Data.Entities.Truck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseSerialColumn();

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<int>("ModelYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("TruckModelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TruckModelId");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("VolvoExam.Data.Entities.TruckModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseSerialColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TruckModel");
                });

            modelBuilder.Entity("VolvoExam.Data.Entities.Truck", b =>
                {
                    b.HasOne("VolvoExam.Data.Entities.TruckModel", "TruckModel")
                        .WithMany("Truck")
                        .HasForeignKey("TruckModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TruckModel");
                });

            modelBuilder.Entity("VolvoExam.Data.Entities.TruckModel", b =>
                {
                    b.Navigation("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
